### ISSUE TITLE
Location Parameter

### ISSUE THREAD

**Issue by krohm** [olohmann/terraform-azure-runner#7]
Please check the location parameter, in Tier 0 and 1 is't not working and alwayds defauting to westeurope, when setting the parameter NOT in IAC_Variables, but in the location parameter of tfvars

**Comment by olohmann** [comment]
Unfortunately, this is controlled via the YAML pipelines outside of this script. The script takes a Location parameter and passes it through to the TF deployment. So you only need to influence the Location parameter to pass through the "location" parameter of the "variables.tf".
